import { MINERS_DATA } from '@/lib/data'

export default function MinersPage() {
  return (
      <main style={{ maxWidth: 1100, margin: '0 auto', padding: '2rem 1rem' }}>
            <h1 style={{ fontSize: '2rem', fontWeight: 700, marginBottom: '0.5rem' }}>Bitcoin Mining Hardware Database</h1>
                  <p style={{ color: '#666', marginBottom: '2rem' }}>Compare ASIC miners by hashrate, efficiency, and price.</p>
                        <div style={{ overflowX: 'auto' }}>
                                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
                                          <thead>
                                                      <tr style={{ borderBottom: '2px solid #e5e7eb', background: '#f9fafb' }}>
                                                                    <th style={{ padding: '0.75rem 1rem', textAlign: 'left' }}>Miner</th>
                                                                                  <th style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>Hashrate</th>
                                                                                                <th style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>Power (W)</th>
                                                                                                              <th style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>J/TH</th>
                                                                                                                            <th style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>Price</th>
                                                                                                                                          <th style={{ padding: '0.75rem 1rem', textAlign: 'left' }}>Cooling</th>
                                                                                                                                                      </tr>
                                                                                                                                                                </thead>
                                                                                                                                                                          <tbody>
                                                                                                                                                                                      {MINERS_DATA.map((m, i) => (
                                                                                                                                                                                                    <tr key={m.id} style={{ borderBottom: '1px solid #e5e7eb', background: i % 2 === 0 ? '#fff' : '#f9fafb' }}>
                                                                                                                                                                                                                    <td style={{ padding: '0.75rem 1rem' }}>
                                                                                                                                                                                                                                      <div style={{ fontWeight: 600 }}>{m.name}</div>
                                                                                                                                                                                                                                                        <div style={{ color: '#888', fontSize: '0.75rem' }}>{m.manufacturer}</div>
                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                        <td style={{ padding: '0.75rem 1rem', textAlign: 'right', fontWeight: 600 }}>{m.hashrate} {m.hashrate_unit}</td>
                                                                                                                                                                                                                                                                                                        <td style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>{m.power_consumption.toLocaleString()}</td>
                                                                                                                                                                                                                                                                                                                        <td style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>
                                                                                                                                                                                                                                                                                                                                          <span style={{ color: m.efficiency < 20 ? '#16a34a' : m.efficiency < 25 ? '#d97706' : '#dc2626' }}>{m.efficiency}</span>
                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                          <td style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>${m.price_usd?.toLocaleString() ?? 'N/A'}</td>
                                                                                                                                                                                                                                                                                                                                                                                          <td style={{ padding: '0.75rem 1rem' }}>{m.cooling_type}</td>
                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
