import { Miner, HostingProvider, GlossaryTerm } from './types'

// Static enriched miner data — used as fallback when Supabase is not connected
// efficiency_j_per_th = power_watts / default_hashrate_th
export const MINERS_DATA: Miner[] = [
  // ── Air-cooled ──────────────────────────────────────────────────────────────
  {
    id: 19, name: 'Antminer S21 XP', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 270, power_watts: 3645, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s21-xp', manufacturer: 'Bitmain', release_date: '2024-07-01',
    market_price_usd: 5200, efficiency_j_per_th: 13.5, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 14.5,
    best_for: 'Large-scale hosted operations seeking the highest air-cooled efficiency available in 2024-2026',
    worst_for: 'Budget-constrained operators — premium price over S21 Pro; not suitable for home use',
    rating: 9.8,
    pros: ['13.5 J/TH — best efficiency of any air-cooled miner available', '270 TH/s is highest air-cooled hashrate on the market', 'Superior post-2028 halving resilience', 'Full Bitmain warranty and support'],
    cons: ['Premium price (~$5,200) vs S21 Pro (~$3,800)', 'Requires 240V / 16A dedicated circuit', '75 dB noise requires industrial environment', 'Limited initial availability'],
    notes: "Bitmain's highest-efficiency air-cooled miner (2024 H2 release)", created_at: '2024-07-01T00:00:00Z',
  },
  {
    id: 1, name: 'Antminer S21 Pro', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 234, power_watts: 3510, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s21-pro', manufacturer: 'Bitmain', release_date: '2024-01-01',
    market_price_usd: 3800, efficiency_j_per_th: 15.0, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 14.4,
    best_for: 'Large-scale hosted operations seeking best-in-class air-cooled efficiency',
    worst_for: 'Home miners — 75 dB noise and 15A+ power draw is unsuitable for residential use',
    rating: 9.5,
    pros: ['Best-in-class 15 J/TH efficiency for air cooling', '234 TH/s industry-leading air hashrate', 'Bitmain warranty and global support network', 'Highest single-unit revenue of any air-cooled miner'],
    cons: ['High upfront cost vs older S19 generation', 'Requires 240V / 15A dedicated circuit', '75 dB noise level requires industrial environment'],
    notes: 'Bitmain flagship air-cooled miner (2024)', created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2, name: 'Antminer S21', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 200, power_watts: 3500, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s21', manufacturer: 'Bitmain', release_date: '2024-01-01',
    market_price_usd: 2700, efficiency_j_per_th: 17.5, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 14.2,
    best_for: 'Hosted operations seeking a balance of cost and S21-generation performance',
    worst_for: 'Home miners and anyone who can stretch budget to the S21 Pro',
    rating: 8.5,
    pros: ['200 TH/s strong hashrate', 'More affordable than S21 Pro', 'Proven Bitmain S21 platform reliability', 'Good resale value retention'],
    cons: ['17.5 J/TH — less efficient than S21 Pro', 'Same 75 dB noise level as S21 Pro', 'Power requirements need industrial setup'],
    notes: null, created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 3, name: 'Antminer S19 XP', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 140, power_watts: 3010, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s19-xp', manufacturer: 'Bitmain', release_date: '2022-06-01',
    market_price_usd: 2000, efficiency_j_per_th: 21.5, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 13.2,
    best_for: 'Operators upgrading from older S19 generation at a lower upfront cost than S21 series',
    worst_for: 'New buyers comparing vs S21 series — price gap has narrowed significantly',
    rating: 7.5,
    pros: ['140 TH/s solid hashrate for the price', 'Lower cost than S21 models', 'Widely supported by all hosting providers', 'Strong secondary market'],
    cons: ['21.5 J/TH is below current best-in-class', 'Higher operating cost per TH than S21 series', 'Older generation approaching end of competitive lifecycle'],
    notes: 'High-efficiency S19 generation', created_at: '2022-06-01T00:00:00Z',
  },
  {
    id: 4, name: 'Antminer S19j Pro+', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 122, power_watts: 3355, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s19j-pro-plus', manufacturer: 'Bitmain', release_date: '2022-01-01',
    market_price_usd: 1350, efficiency_j_per_th: 27.5, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 13.2,
    best_for: 'Budget-conscious operators needing entry into mining at lowest upfront cost',
    worst_for: 'Anyone who can afford newer generation — running costs eat into margins',
    rating: 6.5,
    pros: ['122 TH/s decent hashrate', 'Very affordable purchase price', 'Huge used market availability', 'Proven track record since 2022'],
    cons: ['27.5 J/TH is less competitive at $0.07+ electricity', 'Older generation with higher per-TH operating cost', 'Limited upside vs S21 series at similar hosted margins'],
    notes: null, created_at: '2022-01-01T00:00:00Z',
  },
  {
    id: 5, name: 'Antminer S19j Pro', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 104, power_watts: 3068, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s19j-pro', manufacturer: 'Bitmain', release_date: '2021-08-01',
    market_price_usd: 1000, efficiency_j_per_th: 29.5, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 13.2,
    best_for: 'Entry-level operations on very tight budgets or sub-$0.05/kWh electricity',
    worst_for: 'Standard hosted environments — running cost margins are very thin',
    rating: 6.0,
    pros: ['104 TH/s baseline hashrate', 'Cheapest entry point into modern mining', 'Widely supported by all facilities', 'Massive install base — easy to find support'],
    cons: ['29.5 J/TH relatively inefficient by 2026 standards', 'Narrow to negative margins at typical hosting rates', 'Should only be considered at sub-$0.05/kWh power'],
    notes: null, created_at: '2021-08-01T00:00:00Z',
  },
  {
    id: 6, name: 'Antminer S19 Pro', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 110, power_watts: 3250, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s19-pro', manufacturer: 'Bitmain', release_date: '2020-04-01',
    market_price_usd: 900, efficiency_j_per_th: 29.5, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 13.2,
    best_for: 'Extremely low-cost electricity environments only (below $0.04/kWh)',
    worst_for: 'Standard $0.07+ hosted environments where margins are negative',
    rating: 5.5,
    pros: ['110 TH/s hashrate', 'Very low purchase price', 'Largest existing install base — support is everywhere', 'Simple, well-understood hardware'],
    cons: ['29.5 J/TH means high running costs', 'Negative margins at typical hosted electricity rates', 'End-of-life hardware with declining competitiveness'],
    notes: null, created_at: '2020-04-01T00:00:00Z',
  },
  {
    id: 7, name: 'Canaan Avalon A1566', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 150, power_watts: 3420, spec_confidence: 'verified', is_active: true,
    slug: 'canaan-avalon-a1566', manufacturer: 'Canaan', release_date: '2024-03-01',
    market_price_usd: 2200, efficiency_j_per_th: 22.8, noise_db: 75,
    dimensions: '430×195×295 mm', weight_kg: 14.5,
    best_for: 'Operators wanting a Bitmain alternative with strong 2024-generation hashrate',
    worst_for: 'Efficiency-focused buyers — Bitmain S21 Pro beats it at similar prices',
    rating: 7.0,
    pros: ['150 TH/s competitive hashrate', 'Good alternative to Bitmain ecosystem', 'Canaan after-sales support', 'Competitive market pricing vs Antminer equivalent'],
    cons: ['22.8 J/TH is less efficient than Bitmain S21 series', 'Smaller firmware community', 'Lower resale value vs Antminer brand'],
    notes: null, created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 8, name: 'Canaan Avalon A1466', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 150, power_watts: 3400, spec_confidence: 'verified', is_active: true,
    slug: 'canaan-avalon-a1466', manufacturer: 'Canaan', release_date: '2023-06-01',
    market_price_usd: 1900, efficiency_j_per_th: 22.7, noise_db: 75,
    dimensions: '430×195×295 mm', weight_kg: 14.2,
    best_for: 'Budget buyers in the Canaan ecosystem wanting 2023-generation hashrate',
    worst_for: 'Efficiency-focused operators — 22.7 J/TH is below current leaders',
    rating: 6.5,
    pros: ['150 TH/s competitive hashrate', 'Lower price point vs 2024 models', 'Canaan ecosystem compatibility', 'Good availability'],
    cons: ['22.7 J/TH is below competitive threshold', 'Higher operating cost per TH than S21 series', 'Smaller support community'],
    notes: null, created_at: '2023-06-01T00:00:00Z',
  },
  {
    id: 9, name: 'Canaan Avalon A1366', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 110, power_watts: 3250, spec_confidence: 'verified', is_active: true,
    slug: 'canaan-avalon-a1366', manufacturer: 'Canaan', release_date: '2022-08-01',
    market_price_usd: 1100, efficiency_j_per_th: 29.5, noise_db: 75,
    dimensions: '430×195×290 mm', weight_kg: 14.0,
    best_for: 'Extreme budget entry — only viable at very low electricity costs',
    worst_for: 'Anyone paying standard hosting rates of $0.06+/kWh',
    rating: 5.5,
    pros: ['Very affordable purchase price', 'Simple plug-and-play operation', 'Compatible with all air-cooled hosting facilities'],
    cons: ['29.5 J/TH well below competitive levels', 'Marginal profitability at standard hosting rates', 'Older generation with high operating costs'],
    notes: null, created_at: '2022-08-01T00:00:00Z',
  },
  {
    id: 10, name: 'Whatsminer M60S', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 170, power_watts: 3400, spec_confidence: 'verified', is_active: true,
    slug: 'whatsminer-m60s', manufacturer: 'MicroBT', release_date: '2023-09-01',
    market_price_usd: 2500, efficiency_j_per_th: 20.0, noise_db: 75,
    dimensions: '430×160×360 mm', weight_kg: 14.4,
    best_for: 'Operators seeking a strong Bitmain alternative with modern efficiency',
    worst_for: 'Maximum efficiency seekers — Antminer S21 Pro wins on J/TH',
    rating: 8.0,
    pros: ['170 TH/s strong hashrate', '20 J/TH competitive efficiency', 'MicroBT build quality reputation', 'Good alternative to Antminer brand concentration'],
    cons: ['Less efficient than Antminer S21 Pro at 15 J/TH', 'Smaller firmware and tuning community', 'Resale value below Antminer equivalents'],
    notes: 'MicroBT Whatsminer M60S (standard variant, 170 TH/s)', created_at: '2023-09-01T00:00:00Z',
  },
  {
    id: 21, name: 'Whatsminer M50S', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 126, power_watts: 3276, spec_confidence: 'verified', is_active: true,
    slug: 'whatsminer-m50s', manufacturer: 'MicroBT', release_date: '2022-11-01',
    market_price_usd: 1200, efficiency_j_per_th: 26.0, noise_db: 75,
    dimensions: '430×160×360 mm', weight_kg: 13.5,
    best_for: 'Budget Whatsminer buyers; operators wanting MicroBT hardware at lower cost',
    worst_for: 'Standard hosting at $225/month — 26 J/TH makes margins very thin',
    rating: 6.5,
    pros: ['Affordable entry into Whatsminer ecosystem', 'Reliable MicroBT build quality', 'Compatible with standard hosting facilities', '126 TH/s reasonable baseline'],
    cons: ['26 J/TH is well above competitive efficiency threshold', 'Thin margins at standard hosting rates', 'Outclassed by newer M60S generation'],
    notes: 'MicroBT Whatsminer M50S', created_at: '2022-11-01T00:00:00Z',
  },
  {
    id: 22, name: 'Whatsminer M53S', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 230, power_watts: 6555, spec_confidence: 'verified', is_active: true,
    slug: 'whatsminer-m53s', manufacturer: 'MicroBT', release_date: '2023-05-01',
    market_price_usd: 4800, efficiency_j_per_th: 28.5, noise_db: 45,
    dimensions: '430×160×360 mm', weight_kg: 16.0,
    best_for: 'Hydro operations seeking high absolute hashrate from Whatsminer ecosystem',
    worst_for: 'Efficiency-focused operations — 28.5 J/TH is high for hydro; Antminer hydro models are significantly more efficient',
    rating: 6.8,
    pros: ['230 TH/s very high hashrate', 'MicroBT build quality', 'Near-silent hydro operation', 'Good for maximum hashrate deployments'],
    cons: ['28.5 J/TH is poor efficiency for a hydro miner (S21 Pro Hydro is 16 J/TH)', 'High power draw (6,555W)', 'Requires full hydro cooling infrastructure', 'Outclassed on efficiency by Antminer hydro lineup'],
    notes: 'MicroBT Whatsminer M53S (hydro-cooled)', created_at: '2023-05-01T00:00:00Z',
  },
  // ── Hydro ────────────────────────────────────────────────────────────────────
  {
    id: 20, name: 'Antminer S21 XP Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 473, power_watts: 5676, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s21-xp-hydro', manufacturer: 'Bitmain', release_date: '2024-10-01',
    market_price_usd: 9500, efficiency_j_per_th: 12.0, noise_db: 45,
    dimensions: '400×195×290 mm', weight_kg: 16.8,
    best_for: 'Industrial-scale immersion or hydro facilities seeking maximum hashrate per unit with top-tier efficiency',
    worst_for: 'Operators without dedicated hydro/immersion infrastructure — very high infrastructure barrier',
    rating: 9.9,
    pros: ['473 TH/s — highest hashrate of any commercially available miner', '12 J/TH class-leading efficiency for hydro', 'Near-silent at 45 dB', 'Maximum revenue per rack unit in hydro facilities'],
    cons: ['Requires immersion or hydro infrastructure (not air-cooled)', 'Very high unit price (~$9,500)', 'Limited hosting provider compatibility', 'Higher infrastructure investment required'],
    notes: 'NOTE: Requires immersion or hydro cooling infrastructure. Abundant Mines currently offers air cooling only, with immersion planned for approximately 2028.',
    created_at: '2024-10-01T00:00:00Z',
  },
  {
    id: 11, name: 'Antminer S21 Pro Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 335, power_watts: 5360, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s21-pro-hydro', manufacturer: 'Bitmain', release_date: '2024-03-01',
    market_price_usd: 5500, efficiency_j_per_th: 16.0, noise_db: 45,
    dimensions: '400×195×290 mm', weight_kg: 17.5,
    best_for: 'Large-scale operations with existing hydro cooling infrastructure',
    worst_for: 'Operations without water cooling setup — infrastructure cost is high',
    rating: 9.0,
    pros: ['335 TH/s class-leading air+hydro hashrate', 'Near-silent at 45 dB', 'Extended hardware lifespan with liquid cooling', 'Ideal for high-density rack deployments'],
    cons: ['Requires dedicated hydro cooling infrastructure', 'Higher upfront hardware cost', 'Limited hosting provider compatibility vs air cooling', 'More complex setup and maintenance'],
    notes: 'Liquid cooling required', created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 12, name: 'Antminer S21 Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 319, power_watts: 5360, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s21-hydro', manufacturer: 'Bitmain', release_date: '2024-02-01',
    market_price_usd: 5000, efficiency_j_per_th: 16.8, noise_db: 45,
    dimensions: '400×195×290 mm', weight_kg: 17.2,
    best_for: 'Large operations with hydro infrastructure wanting strong hashrate at lower cost than S21 Pro Hydro',
    worst_for: 'Operations without hydro cooling — high infrastructure barrier',
    rating: 8.8,
    pros: ['319 TH/s exceptional hashrate', 'Low 45 dB noise profile', 'Liquid cooling extends lifespan', 'Lower price than S21 Pro Hydro'],
    cons: ['Requires hydro cooling infrastructure', 'Higher per-unit cost than air models', 'Fewer compatible hosting facilities'],
    notes: null, created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 13, name: 'Antminer S19 XP Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 255, power_watts: 5346, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s19-xp-hydro', manufacturer: 'Bitmain', release_date: '2022-08-01',
    market_price_usd: 2800, efficiency_j_per_th: 21.0, noise_db: 45,
    dimensions: '400×195×290 mm', weight_kg: 16.5,
    best_for: 'S19-generation hydro upgrade path — lower cost entry into hydro mining',
    worst_for: 'New buyers who can access S21 Hydro at competitive pricing',
    rating: 7.5,
    pros: ['255 TH/s strong hydro hashrate', 'Low noise operation', 'Good price vs S21 Hydro generation', 'Compatible with existing S19 hydro infrastructure'],
    cons: ['21 J/TH not as efficient as S21 Hydro generation', 'Older generation with shorter remaining lifecycle', 'Still requires full hydro infrastructure investment'],
    notes: 'Significantly higher hash than air variant', created_at: '2022-08-01T00:00:00Z',
  },
  {
    id: 14, name: 'Antminer S19 Pro+ Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 198, power_watts: 5445, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s19-pro-plus-hydro', manufacturer: 'Bitmain', release_date: '2022-04-01',
    market_price_usd: 2300, efficiency_j_per_th: 27.5, noise_db: 45,
    dimensions: '400×195×290 mm', weight_kg: 16.5,
    best_for: 'Budget hydro entry with existing S19 hydro infrastructure',
    worst_for: 'Anyone focused on efficiency — 27.5 J/TH is below competitive levels',
    rating: 6.5,
    pros: ['198 TH/s above-average hashrate', 'Quiet hydro operation at 45 dB', 'Lower cost than S21 Hydro series', 'Bitmain ecosystem compatibility'],
    cons: ['27.5 J/TH is well below S21 Hydro efficiency', 'Higher running cost per TH', 'Older hardware generation with limited lifecycle'],
    notes: null, created_at: '2022-04-01T00:00:00Z',
  },
  {
    id: 15, name: 'Whatsminer M63S Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 390, power_watts: 7215, spec_confidence: 'pending_verification', is_active: true,
    slug: 'whatsminer-m63s-hydro', manufacturer: 'MicroBT', release_date: '2024-06-01',
    market_price_usd: 7000, efficiency_j_per_th: 18.5, noise_db: 40,
    dimensions: '430×160×360 mm', weight_kg: 20.0,
    best_for: 'Large-scale hydro deployments seeking maximum hashrate per unit',
    worst_for: 'Small operators — very high unit cost requires significant capital',
    rating: 8.5,
    pros: ['390 TH/s industry-leading hashrate', 'Extremely quiet at 40 dB', 'MicroBT build quality', 'Future-proof for 2026-2028 difficulty growth'],
    cons: ['Specs pending verification with MicroBT', 'Very high unit price requires large capital deployment', 'Requires purpose-built hydro infrastructure', 'Limited deployment history — newer hardware'],
    notes: 'Verify latest revision with MicroBT', created_at: '2024-06-01T00:00:00Z',
  },
  // ── Immersion ────────────────────────────────────────────────────────────────
  {
    id: 16, name: 'Antminer S19 XP Immersion', algorithm: 'SHA-256', cooling_type: 'immersion',
    default_hashrate_th: 255, power_watts: 2900, spec_confidence: 'pending_verification', is_active: true,
    slug: 'antminer-s19-xp-immersion', manufacturer: 'Bitmain', release_date: '2023-01-01',
    market_price_usd: 2500, efficiency_j_per_th: 11.4, noise_db: 30,
    dimensions: '400×195×290 mm', weight_kg: 13.5,
    best_for: 'Large-scale immersion deployments seeking low operating cost and hardware longevity',
    worst_for: 'Operations without immersion tank infrastructure — high setup barrier',
    rating: 8.5,
    pros: ['Outstanding 11.4 J/TH efficiency in immersion', 'Near-silent operation at 30 dB', 'Dielectric fluid extends hardware lifespan significantly', '255 TH/s strong hashrate'],
    cons: ['Specs pending manufacturer confirmation from Bitmain', 'Requires full immersion tank and dielectric fluid', 'High infrastructure setup cost', 'Very limited hosting provider support'],
    notes: 'Estimated ~10-15% power reduction vs air — verify with Bitmain', created_at: '2023-01-01T00:00:00Z',
  },
  {
    id: 17, name: 'Whatsminer M50S++ Immersion', algorithm: 'SHA-256', cooling_type: 'immersion',
    default_hashrate_th: 230, power_watts: 3600, spec_confidence: 'pending_verification', is_active: true,
    slug: 'whatsminer-m50s-plus-plus-immersion', manufacturer: 'MicroBT', release_date: '2023-06-01',
    market_price_usd: 2700, efficiency_j_per_th: 15.7, noise_db: 30,
    dimensions: '430×160×360 mm', weight_kg: 14.8,
    best_for: 'Immersion operators in the MicroBT ecosystem',
    worst_for: 'Operations without existing immersion infrastructure',
    rating: 8.0,
    pros: ['230 TH/s strong immersion hashrate', 'Very quiet in immersion fluid', 'MicroBT build quality and reliability', 'Hardware lifespan extension in dielectric fluid'],
    cons: ['Specs pending contact with MicroBT', 'Requires immersion infrastructure investment', 'More complex maintenance than air cooling', 'Limited verified performance data'],
    notes: 'Immersion-optimised variant — contact MicroBT to confirm', created_at: '2023-06-01T00:00:00Z',
  },
  {
    id: 18, name: 'Antminer S21 Pro Immersion', algorithm: 'SHA-256', cooling_type: 'immersion',
    default_hashrate_th: 270, power_watts: 3300, spec_confidence: 'pending_verification', is_active: true,
    slug: 'antminer-s21-pro-immersion', manufacturer: 'Bitmain', release_date: '2024-06-01',
    market_price_usd: 4000, efficiency_j_per_th: 12.2, noise_db: 30,
    dimensions: '400×195×290 mm', weight_kg: 14.5,
    best_for: 'Maximum efficiency immersion operations at industrial scale',
    worst_for: 'Anyone without immersion infrastructure — this is the most infrastructure-intensive option',
    rating: 9.0,
    pros: ['12.2 J/TH exceptional immersion efficiency', '270 TH/s strong hashrate', 'Near-silent at 30 dB', 'Best long-term economics at scale with lowest per-TH energy cost'],
    cons: ['Specs estimated from air-cooled equivalent — pending manufacturer confirmation', 'Requires full immersion tanks and dielectric fluid system', 'Highest total infrastructure investment', 'Very few compatible hosting facilities'],
    notes: 'Estimated from air-cooled equivalent — pending manufacturer confirmation', created_at: '2024-06-01T00:00:00Z',
  },
  // ── New 2025 models ──────────────────────────────────────────────────────────
  {
    id: 23, name: 'Antminer S23', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 280, power_watts: 3640, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s23', manufacturer: 'Bitmain', release_date: '2025-01-01',
    market_price_usd: 5800, efficiency_j_per_th: 13.0, noise_db: 75,
    dimensions: '400×195×290 mm', weight_kg: 14.6,
    best_for: 'Large-scale operations seeking the latest Bitmain air-cooled generation with best-in-class efficiency',
    worst_for: 'Budget-constrained buyers — premium price over S21 XP; not suitable for home use',
    rating: 9.9,
    pros: ['280 TH/s highest air-cooled hashrate available', '13.0 J/TH best air-cooled efficiency on the market', 'Strong post-halving resilience', 'Full Bitmain warranty and support'],
    cons: ['Premium price (~$5,800)', 'Requires 240V / 16A dedicated circuit', '75 dB noise requires industrial environment', 'Latest generation — limited secondary market'],
    notes: "Bitmain's 2025 flagship air-cooled ASIC", created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 24, name: 'Antminer S23 Hydro', algorithm: 'SHA-256', cooling_type: 'hydro',
    default_hashrate_th: 490, power_watts: 5880, spec_confidence: 'verified', is_active: true,
    slug: 'antminer-s23-hydro', manufacturer: 'Bitmain', release_date: '2025-03-01',
    market_price_usd: 10500, efficiency_j_per_th: 12.0, noise_db: 45,
    dimensions: '400×195×290 mm', weight_kg: 17.0,
    best_for: 'Industrial hydro facilities seeking the highest hashrate per unit available in 2025',
    worst_for: 'Operators without hydro infrastructure — very high infrastructure and capital barrier',
    rating: 10.0,
    pros: ['490 TH/s highest hashrate of any production miner', '12.0 J/TH exceptional hydro efficiency', 'Near-silent 45 dB operation', 'Maximum revenue per rack slot in hydro facilities'],
    cons: ['Requires hydro/immersion infrastructure', 'Very high unit price (~$10,500)', 'Limited hosting provider compatibility', 'High infrastructure investment'],
    notes: "Bitmain's 2025 flagship hydro-cooled ASIC — highest hashrate in production", created_at: '2025-03-01T00:00:00Z',
  },
  {
    id: 25, name: 'Whatsminer M60S+', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 186, power_watts: 3534, spec_confidence: 'verified', is_active: true,
    slug: 'whatsminer-m60s-plus', manufacturer: 'MicroBT', release_date: '2024-06-01',
    market_price_usd: 2900, efficiency_j_per_th: 19.0, noise_db: 75,
    dimensions: '430×160×360 mm', weight_kg: 14.6,
    best_for: 'Operators wanting the latest Whatsminer air-cooled generation with 186 TH/s',
    worst_for: 'Maximum efficiency seekers — Antminer S21 Pro remains more efficient at 15 J/TH',
    rating: 8.2,
    pros: ['186 TH/s strong hashrate', '19.0 J/TH competitive efficiency', 'Latest M60 generation hardware', 'MicroBT build quality'],
    cons: ['Less efficient than Antminer S21 Pro (15 J/TH)', 'Premium price vs M60S', 'Smaller firmware community vs Bitmain'],
    notes: 'MicroBT Whatsminer M60S+ (boosted variant, 186 TH/s)', created_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 26, name: 'Whatsminer M70', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 230, power_watts: 3220, spec_confidence: 'verified', is_active: true,
    slug: 'whatsminer-m70', manufacturer: 'MicroBT', release_date: '2025-01-01',
    market_price_usd: 4500, efficiency_j_per_th: 14.0, noise_db: 75,
    dimensions: '430×160×360 mm', weight_kg: 15.0,
    best_for: 'Operators seeking a top-tier Bitmain alternative with 2025-generation efficiency',
    worst_for: 'Buyers focused solely on cost — premium price for MicroBT flagship',
    rating: 9.3,
    pros: ['230 TH/s exceptional air-cooled hashrate', '14.0 J/TH near best-in-class efficiency', 'Strong Whatsminer build quality reputation', 'Excellent portfolio diversification from Bitmain'],
    cons: ['Premium price (~$4,500)', 'Smaller tuning/firmware community vs Antminer', 'Limited hosting provider familiarity with new generation'],
    notes: 'MicroBT Whatsminer M70 (2025 flagship air-cooled)', created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 27, name: 'Whatsminer M70S', algorithm: 'SHA-256', cooling_type: 'air',
    default_hashrate_th: 240, power_watts: 3360, spec_confidence: 'verified', is_active: true,
    slug: 'whatsminer-m70s', manufacturer: 'MicroBT', release_date: '2025-02-01',
    market_price_usd: 5000, efficiency_j_per_th: 14.0, noise_db: 75,
    dimensions: '430×160×360 mm', weight_kg: 15.2,
    best_for: 'Operators seeking maximum hashrate in the Whatsminer 2025 air-cooled lineup',
    worst_for: 'Budget-constrained buyers — highest-spec Whatsminer commands a premium',
    rating: 9.5,
    pros: ['240 TH/s highest air-cooled Whatsminer hashrate', '14.0 J/TH best-in-class Whatsminer efficiency', 'Near-equivalent to Antminer S23 specs at competitive price', 'Portfolio diversification from Bitmain'],
    cons: ['Premium price (~$5,000)', 'Newer generation with limited track record', 'Fewer firmware optimization options vs Antminer'],
    notes: 'MicroBT Whatsminer M70S (2025 flagship, boosted variant)', created_at: '2025-02-01T00:00:00Z',
  },
]

export const PROVIDERS_DATA: HostingProvider[] = [
  {
    id: 'abundant-miners',
    name: 'Abundant Miners',
    tier: 1,
    country: 'US',
    facilityLocations: ['United States'],
    website: 'https://abundantminers.com',
    contactEmail: 'contact@abundantminers.com',
    lastVerified: '2025-12-01',
    rateMin: null,
    rateMax: null,
    flatMonthly: 225,
    billingType: 'flat',
    setupFee: 500,
    repairPolicy: 'Equipment insurance included; routine maintenance covered in flat monthly fee',
    hiddenFees: null,
    cooling: ['air'],
    powerSource: 'Grid (US)',
    capacityMW: null,
    uptimePercent: 99.0,
    minMachines: 1,
    contractLength: '1yr',
    financingAvailable: true,
    insuranceAvailable: true,
    customerOwnedMiners: true,
    minerPurchaseProgram: false,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: false,
    affiliateProgram: true,
    affiliateRate: 'Commission on referrals',
    affiliateLink: 'https://abundantmines.com/ref/72/',
    verified: true,
    verificationStatus: 'verified',
    lightningScore: 94,
    description: 'The most beginner-friendly hosting option with a flat $225/month all-in fee covering electricity, cooling, maintenance, insurance, and internet. No surprise bills. Rate locked for 12 months. Financing available up to $140k.',
    pros: ['Flat $225/month — electricity, cooling, maintenance, insurance, internet all included', '12-month rate lock protects against electricity price increases', 'Full pool and firmware flexibility — use any pool you choose', 'Financing available up to $140k at 10% APR over 36 months', 'Insurance included on all equipment', 'Only $500 deposit required to get started'],
    cons: ['Air cooling only until ~2027 — hydro and immersion in development', '12-month minimum contract', 'Only US-based locations currently'],
    bestFor: 'Beginners and small operators wanting predictable flat-fee costs with no surprise bills',
  },
  {
    id: 'simple-mining',
    name: 'Simple Mining',
    tier: 2,
    country: 'US',
    facilityLocations: ['Iowa'],
    website: 'https://simplemining.io',
    contactEmail: 'contact@simplemining.io',
    lastVerified: '2026-06-01',
    rateMin: 0.075,
    rateMax: 0.075,
    flatMonthly: null,
    billingType: 'kwh',
    setupFee: null,
    repairPolicy: 'Contact provider for repair and maintenance policy',
    hiddenFees: null,
    cooling: ['air', 'hydro'],
    powerSource: 'Grid (Iowa)',
    capacityMW: null,
    uptimePercent: null,
    minMachines: 1,
    contractLength: 'flexible',
    financingAvailable: false,
    insuranceAvailable: false,
    customerOwnedMiners: true,
    minerPurchaseProgram: false,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: false,
    affiliateProgram: false,
    affiliateRate: null,
    affiliateLink: null,
    verified: true,
    verificationStatus: 'verified',
    lightningScore: 78,
    description: 'Iowa-based hosting facility offering air and hydro cooling at an all-in rate of $0.075/kWh. One of the few mid-range providers supporting both air and hydro-cooled hardware under the same roof.',
    pros: ['$0.075/kWh all-in — clear predictable cost', 'Both air and hydro cooling available', 'Iowa location offers low-cost grid power', 'Minimum 1 machine — accessible to small operators'],
    cons: ['Single Iowa facility — no geographic redundancy', 'Per-kWh billing less predictable than flat-fee', 'No immersion cooling option'],
    bestFor: 'Operators who need air or hydro cooling at a known all-in rate in a low-cost Iowa facility',
  },
  {
    id: 'ez-blockchain',
    name: 'EZ Blockchain',
    tier: 2,
    country: 'US',
    facilityLocations: ['Texas', 'Wyoming', 'Nebraska'],
    website: 'https://ezblockchain.net',
    contactEmail: 'contact@ezblockchain.net',
    lastVerified: '2026-06-01',
    rateMin: 0.07,
    rateMax: 0.07,
    flatMonthly: null,
    billingType: 'kwh',
    setupFee: null,
    repairPolicy: 'Contact provider for repair and maintenance policy',
    hiddenFees: null,
    cooling: ['air'],
    powerSource: 'Natural gas + grid (TX/WY/NE)',
    capacityMW: null,
    uptimePercent: null,
    minMachines: null,
    contractLength: 'flexible',
    financingAvailable: false,
    insuranceAvailable: false,
    customerOwnedMiners: true,
    minerPurchaseProgram: false,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: false,
    affiliateProgram: false,
    affiliateRate: null,
    affiliateLink: null,
    verified: true,
    verificationStatus: 'verified',
    lightningScore: 75,
    description: 'US-based hosting provider with facilities in Texas, Wyoming, and Nebraska. All-in rate of $0.07/kWh covers electricity, cooling, and basic management. Air cooling only.',
    pros: ['$0.07/kWh all-in — competitive rate across TX/WY/NE', 'Multiple US state locations reduce single-facility risk', 'Established track record in energy cost efficiency', 'Simple per-kWh billing structure'],
    cons: ['Air cooling only — hydro and immersion miners not supported', 'Per-kWh billing less predictable than flat-fee', 'Contract minimums not publicly stated'],
    bestFor: 'Cost-focused air-cooling operators wanting a competitive all-in rate across multiple US states',
  },
  {
    id: 'sazmining',
    name: 'Sazmining',
    tier: 2,
    country: 'PY',
    facilityLocations: ['Paraguay'],
    website: 'https://sazmining.com',
    contactEmail: 'contact@sazmining.com',
    lastVerified: '2026-06-01',
    rateMin: 0.045,
    rateMax: 0.050,
    flatMonthly: null,
    billingType: 'kwh',
    setupFee: null,
    repairPolicy: 'Contact provider for repair and maintenance policy',
    hiddenFees: 'Shipping and customs costs for hardware delivery to Paraguay — factor into total deployment cost',
    cooling: ['air'],
    powerSource: 'Hydroelectric (Paraguay)',
    capacityMW: null,
    uptimePercent: null,
    minMachines: 1,
    contractLength: 'flexible',
    financingAvailable: false,
    insuranceAvailable: false,
    customerOwnedMiners: true,
    minerPurchaseProgram: false,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: true,
    affiliateProgram: false,
    affiliateRate: null,
    affiliateLink: null,
    verified: true,
    verificationStatus: 'verified',
    lightningScore: 72,
    description: 'Paraguay-based hosting leveraging low-cost hydroelectric power. Among the lowest electricity rates available to retail miners at approximately $0.045–$0.050/kWh. Air cooling only. International hosting introduces jurisdictional and operational risks to weigh against the cost savings.',
    pros: ['Among the lowest electricity rates available to retail miners', 'Hydroelectric power — renewable and low-cost', 'Air cooling — wide miner compatibility', 'Accessible minimums for small operators'],
    cons: ['International facility — not US-based', 'Jurisdictional risk in Paraguay', 'Shipping and customs costs for hardware delivery', 'KYC required'],
    bestFor: 'Cost-focused operators comfortable with international hosting who want the lowest possible electricity rate',
  },
  {
    id: 'compass-mining',
    name: 'Compass Mining',
    tier: 2,
    country: 'US',
    facilityLocations: ['United States', 'Canada', 'Finland', 'Iceland', 'Norway'],
    website: 'https://compassmining.io',
    contactEmail: 'support@compassmining.io',
    lastVerified: '2025-12-01',
    rateMin: null,
    rateMax: null,
    flatMonthly: null,
    billingType: 'kwh',
    setupFee: null,
    repairPolicy: 'Varies by facility — confirm repair and maintenance terms in your specific facility contract',
    hiddenFees: 'Rates and fees vary significantly by facility; review each individual facility contract carefully',
    cooling: ['air', 'immersion'],
    powerSource: 'Mixed (varies by facility)',
    capacityMW: null,
    uptimePercent: 98.0,
    minMachines: 1,
    contractLength: 'flexible',
    financingAvailable: false,
    insuranceAvailable: false,
    customerOwnedMiners: true,
    minerPurchaseProgram: false,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: true,
    affiliateProgram: true,
    affiliateRate: null,
    affiliateLink: null,
    verified: true,
    verificationStatus: 'contact_only',
    lightningScore: 65,
    description: 'One of the largest Bitcoin mining hosting marketplaces with facilities across the US, Canada, and Nordics. Multiple facility options let you choose your preferred location. Pricing and terms vary by site — contact for a quote.',
    pros: ['Global locations across US, Canada, and Nordic countries', 'Marketplace model with multiple facility choices', 'Air and immersion cooling options available', 'Established platform since 2019'],
    cons: ['No public rate card — pricing by facility contact', 'Quality and pricing vary significantly by facility', 'Some facilities have had historical uptime issues', 'Customer support response times can be slow'],
    bestFor: 'Large-scale operators wanting flexible global contracts and marketplace access',
  },
  {
    id: 'blockware-solutions',
    name: 'Blockware Solutions',
    tier: 3,
    country: 'US',
    facilityLocations: ['United States'],
    website: 'https://blockwaresolutions.com',
    contactEmail: 'info@blockwaresolutions.com',
    lastVerified: '2025-12-01',
    rateMin: null,
    rateMax: null,
    flatMonthly: null,
    billingType: 'kwh',
    setupFee: null,
    repairPolicy: 'Contact provider for repair and maintenance policy',
    hiddenFees: null,
    cooling: ['air'],
    powerSource: 'Grid (US)',
    capacityMW: null,
    uptimePercent: null,
    minMachines: null,
    contractLength: 'flexible',
    financingAvailable: false,
    insuranceAvailable: false,
    customerOwnedMiners: true,
    minerPurchaseProgram: true,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: false,
    affiliateProgram: false,
    affiliateRate: null,
    affiliateLink: null,
    verified: true,
    verificationStatus: 'contact_only',
    lightningScore: 55,
    description: 'Mining solutions provider offering combined hardware sourcing and hosting services in the US. Known for their Bitcoin mining intelligence research. Air cooling only. Pricing by contact.',
    pros: ['Hardware + hosting bundle option simplifies procurement', 'Mining intelligence research and market data', 'US-based operations'],
    cons: ['Air cooling only', 'Smaller operation than major providers', 'No public pricing — contact required', 'Fewer locations than larger providers'],
    bestFor: 'Operators who want combined hardware sourcing and hosting from one provider',
  },
  {
    id: 'hut-8',
    name: 'Hut 8',
    tier: 3,
    country: 'US',
    facilityLocations: ['United States'],
    website: 'https://hut8.com',
    contactEmail: 'ir@hut8.com',
    lastVerified: '2026-06-01',
    rateMin: null,
    rateMax: null,
    flatMonthly: null,
    billingType: 'kwh',
    setupFee: null,
    repairPolicy: 'Institutional SLA — contact for specific repair and maintenance terms',
    hiddenFees: null,
    cooling: ['air', 'immersion'],
    powerSource: 'Grid (US, 15 sites)',
    capacityMW: null,
    uptimePercent: 99.0,
    minMachines: null,
    contractLength: 'flexible',
    financingAvailable: false,
    insuranceAvailable: false,
    customerOwnedMiners: true,
    minerPurchaseProgram: false,
    poolOptions: ['Any pool — full freedom'],
    kycRequired: true,
    affiliateProgram: false,
    affiliateRate: null,
    affiliateLink: null,
    verified: true,
    verificationStatus: 'contact_only',
    lightningScore: 60,
    description: 'Publicly traded Bitcoin mining company (NASDAQ: HUT) operating 15 US sites. Enterprise-grade infrastructure with institutional SLAs. Custom pricing by negotiation — best suited for large fleet operators.',
    pros: ['15 US sites — significant geographic redundancy', 'Publicly traded — transparent financials', 'Institutional-grade infrastructure and SLAs', 'Both air and immersion cooling available'],
    cons: ['No public rate card — pricing by negotiation', 'Institutional minimums not suitable for retail miners', 'Primary focus is self-mining; third-party hosting is secondary'],
    bestFor: 'Large institutional operators wanting a publicly accountable, multi-site US hosting partner',
  },
]

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 1,
    term: 'Hashrate',
    definition: 'The speed at which a mining machine processes Bitcoin transactions, measured in terahashes per second (TH/s)',
    extended_explanation: 'Higher hashrate means more chances to find a block and earn Bitcoin rewards. A machine with 200 TH/s attempts 200 trillion calculations per second. The network-wide hashrate represents the total computing power securing the Bitcoin network.',
    related_terms: ['Terahash (TH/s)', 'Hashprice', 'Network Difficulty'],
  },
  {
    id: 2,
    term: 'Terahash (TH/s)',
    definition: 'One trillion hash computations per second — the standard unit for measuring Bitcoin miner performance',
    extended_explanation: 'Modern miners range from 100 TH/s for older models to 300+ TH/s for the latest hardware. The total Bitcoin network hashrate is measured in exahashes (EH/s) — one quintillion hashes per second. As of 2026, the network runs at approximately 800+ EH/s.',
    related_terms: ['Hashrate', 'J/TH (Joules per Terahash)', 'ASIC Miner'],
  },
  {
    id: 3,
    term: 'Network Difficulty',
    definition: 'A measure of how hard it is to find a new Bitcoin block, automatically adjusted every 2016 blocks (approximately 2 weeks)',
    extended_explanation: 'As more miners join the network, difficulty increases — making it harder for any individual miner to earn rewards. This is the biggest variable in long-term profitability. A 20% difficulty increase directly reduces your mining revenue by 20%. Difficulty adjustments happen approximately every two weeks based on how fast the previous 2016 blocks were found.',
    related_terms: ['Hashrate', 'Block Reward', 'Hashprice'],
  },
  {
    id: 4,
    term: 'Block Reward',
    definition: 'The amount of Bitcoin awarded to the miner who successfully adds a new block to the blockchain',
    extended_explanation: 'Currently 3.125 BTC per block after the April 2024 halving. The next halving in 2028 will reduce this to 1.5625 BTC. Block rewards are the primary income for miners, though transaction fees are becoming increasingly significant.',
    related_terms: ['Bitcoin Halving', 'Mining ROI', 'Hashprice'],
  },
  {
    id: 5,
    term: 'Air Cooling',
    definition: 'The standard method of cooling Bitcoin miners using fans to move air across heat-generating components',
    extended_explanation: 'Most cost-effective for small to medium operations. Requires good ventilation and dust management. Suitable for Antminer S19 and S21 series standard models. Noise levels typically 72-78 dB. Infrastructure cost is lowest of the three cooling methods.',
    related_terms: ['Hydro Cooling', 'Immersion Cooling', 'J/TH (Joules per Terahash)'],
  },
  {
    id: 6,
    term: 'Hydro Cooling',
    definition: 'A cooling method that circulates water or coolant through the miner to remove heat more efficiently than air',
    extended_explanation: 'Allows higher overclocking, lower noise (typically 40-50 dB), and better efficiency. Requires more infrastructure investment including plumbing and coolant management. Supported by Antminer S21 Hydro series. Infrastructure cost 2-5x air cooling.',
    related_terms: ['Air Cooling', 'Immersion Cooling', 'J/TH (Joules per Terahash)'],
  },
  {
    id: 7,
    term: 'Immersion Cooling',
    definition: 'The most advanced cooling method where miners are submerged in non-conductive dielectric fluid',
    extended_explanation: 'Dramatically extends hardware lifespan (3-5x vs air), enables maximum overclocking, lowest noise (under 35 dB). Highest upfront infrastructure cost ($10k+ per tank) but best long-term economics at scale. Power consumption can be reduced 10-15% vs air cooling. Used by large-scale operations and specialist hosting providers.',
    related_terms: ['Hydro Cooling', 'Air Cooling', 'Mining at Scale'],
  },
  {
    id: 8,
    term: 'kWh (Kilowatt Hour)',
    definition: 'The standard unit for measuring electricity consumption and cost in mining operations',
    extended_explanation: 'A miner using 3500 watts running for one hour consumes 3.5 kWh. At $0.07 per kWh that costs $0.245 per hour or $5.88 per day. Electricity cost is typically the largest ongoing expense for miners — small differences in kWh rate compound significantly over time.',
    related_terms: ['J/TH (Joules per Terahash)', 'Breakeven', 'Mining ROI'],
  },
  {
    id: 9,
    term: 'J/TH (Joules per Terahash)',
    definition: 'The efficiency rating of a Bitcoin miner — how much energy it uses to produce one terahash of mining power',
    extended_explanation: 'Lower is better. The Antminer S21 Pro achieves approximately 15 J/TH making it one of the most efficient air-cooled miners available. Older miners at 30+ J/TH use twice the electricity for the same hashrate. In immersion, the same hardware can achieve 10-12 J/TH due to cooler operating temperatures.',
    related_terms: ['kWh (Kilowatt Hour)', 'Hashrate', 'Air Cooling'],
  },
  {
    id: 10,
    term: 'ASIC Miner',
    definition: 'Application-Specific Integrated Circuit — a computer chip designed exclusively for Bitcoin mining',
    extended_explanation: 'Unlike GPUs which can mine multiple cryptocurrencies, ASICs are purpose-built for SHA-256 Bitcoin mining, making them far more efficient. Modern ASICs from Bitmain (Antminer), MicroBT (Whatsminer), and Canaan (Avalon) dominate the market. Once purchased, an ASIC can only mine SHA-256 cryptocurrencies.',
    related_terms: ['Hashrate', 'J/TH (Joules per Terahash)', 'Bitcoin Halving'],
  },
  {
    id: 11,
    term: 'Bitcoin Halving',
    definition: 'The event occurring every 210,000 blocks (approximately 4 years) where the Bitcoin block reward is cut in half',
    extended_explanation: 'Previous halvings occurred in 2012 (50→25 BTC), 2016 (25→12.5 BTC), 2020 (12.5→6.25 BTC), and 2024 (6.25→3.125 BTC). Each halving reduces new Bitcoin supply and historically precedes significant price increases. The next halving in 2028 will reduce the block reward to 1.5625 BTC.',
    related_terms: ['Block Reward', 'Mining ROI', 'Hashprice'],
  },
  {
    id: 12,
    term: 'Mining Pool',
    definition: 'A group of miners who combine their hashrate to increase their collective chances of earning block rewards',
    extended_explanation: 'Solo mining is extremely unlikely to find blocks at individual miner scale. Pools distribute rewards proportionally based on contributed hashrate. Popular pools include Foundry USA (largest by hashrate), Antpool, and F2Pool. Most pools charge 1-3% fee. Pool flexibility — the ability to choose your own pool — is a key hosting contract consideration.',
    related_terms: ['Hashrate', 'Block Reward', 'Hashprice'],
  },
  {
    id: 13,
    term: 'Breakeven',
    definition: 'The point at which cumulative mining revenue equals the total cost of hardware plus hosting fees',
    extended_explanation: 'A miner costing $8,000 earning $25 per day net profit reaches breakeven in 320 days. Understanding breakeven is critical before any hardware purchase. Breakeven analysis should be run at current BTC prices AND at stress-test scenarios ($50k, $75k BTC) to understand downside risk.',
    related_terms: ['Mining ROI', 'Hashprice', 'kWh (Kilowatt Hour)'],
  },
  {
    id: 14,
    term: 'Hashprice',
    definition: 'The daily revenue generated per terahash of mining power, expressed in USD per TH/s per day',
    extended_explanation: 'Hashprice combines BTC price and network difficulty into a single profitability metric. It fluctuates daily and is the fastest way to track mining economics. Formula: (BTC price × block reward × 86400 seconds) / (difficulty × 2^32). When hashprice drops below your electricity cost per TH, you\'re losing money.',
    related_terms: ['Network Difficulty', 'Block Reward', 'Breakeven'],
  },
  {
    id: 15,
    term: 'Mining ROI',
    definition: 'Return on Investment — the percentage return on your total mining capital over a given period',
    extended_explanation: 'Calculated as (total mining revenue minus total costs) divided by initial hardware cost. A positive ROI means the operation is profitable. Mining ROI is highly variable — BTC price and network difficulty can shift ROI from positive to negative. Always model ROI across multiple BTC price scenarios before investing.',
    related_terms: ['Breakeven', 'Hashprice', 'Bitcoin Halving'],
  },
]

export function getMinerBySlug(slug: string): Miner | undefined {
  return MINERS_DATA.find(m => m.slug === slug)
}

export function getProviderBySlug(slug: string): HostingProvider | undefined {
  return PROVIDERS_DATA.find(p => p.id === slug)
}

export function getCompatibleProviders(coolingType: string): HostingProvider[] {
  return PROVIDERS_DATA.filter(p => p.cooling.includes(coolingType as 'air' | 'hydro' | 'immersion'))
}

export function getRelatedMiners(miner: Miner, count = 3): Miner[] {
  return MINERS_DATA
    .filter(m => m.slug !== miner.slug && m.cooling_type === miner.cooling_type && m.is_active)
    .sort((a, b) => (b.rating || 0) - (a.rating || 0))
    .slice(0, count)
}
