// Mining hardware data
export const MINERS_DATA = [
  {
    id: 1,
    name: 'Antminer S21 XP',
    manufacturer: 'Bitmain',
    hashrate: 234,
    hashrate_unit: 'TH/s',
    power_consumption: 3360,
    power_unit: 'W',
    efficiency: 14.36,
    efficiency_unit: 'J/TH',
    price_usd: 8500,
    release_date: '2023-11',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 2,
    name: 'Antminer S21',
    manufacturer: 'Bitmain',
    hashrate: 200,
    hashrate_unit: 'TH/s',
    power_consumption: 3010,
    power_unit: 'W',
    efficiency: 15.05,
    efficiency_unit: 'J/TH',
    price_usd: 6500,
    release_date: '2023-09',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 3,
    name: 'Antminer S19 Pro XP',
    manufacturer: 'Bitmain',
    hashrate: 140,
    hashrate_unit: 'TH/s',
    power_consumption: 2700,
    power_unit: 'W',
    efficiency: 19.29,
    efficiency_unit: 'J/TH',
    price_usd: 5200,
    release_date: '2021-06',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 4,
    name: 'Whatsminer M60S',
    manufacturer: 'MicroBT',
    hashrate: 156,
    hashrate_unit: 'TH/s',
    power_consumption: 3354,
    power_unit: 'W',
    efficiency: 21.5,
    efficiency_unit: 'J/TH',
    price_usd: 4800,
    release_date: '2023-09',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 5,
    name: 'Whatsminer M50S',
    manufacturer: 'MicroBT',
    hashrate: 132,
    hashrate_unit: 'TH/s',
    power_consumption: 2997,
    power_unit: 'W',
    efficiency: 22.7,
    efficiency_unit: 'J/TH',
    price_usd: 4200,
    release_date: '2023-05',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 6,
    name: 'Antminer S19 Pro',
    manufacturer: 'Bitmain',
    hashrate: 110,
    hashrate_unit: 'TH/s',
    power_consumption: 1950,
    power_unit: 'W',
    efficiency: 17.73,
    efficiency_unit: 'J/TH',
    price_usd: 3500,
    release_date: '2021-05',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 7,
    name: 'Whatsminer M30S++',
    manufacturer: 'MicroBT',
    hashrate: 112,
    hashrate_unit: 'TH/s',
    power_consumption: 3472,
    power_unit: 'W',
    efficiency: 31.0,
    efficiency_unit: 'J/TH',
    price_usd: 3000,
    release_date: '2021-07',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 8,
    name: 'Antminer T19',
    manufacturer: 'Bitmain',
    hashrate: 84,
    hashrate_unit: 'TH/s',
    power_consumption: 2700,
    power_unit: 'W',
    efficiency: 32.14,
    efficiency_unit: 'J/TH',
    price_usd: 2800,
    release_date: '2019-06',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 9,
    name: 'Antminer S19',
    manufacturer: 'Bitmain',
    hashrate: 110,
    hashrate_unit: 'TH/s',
    power_consumption: 1725,
    power_unit: 'W',
    efficiency: 15.68,
    efficiency_unit: 'J/TH',
    price_usd: 2500,
    release_date: '2020-05',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 10,
    name: 'Antminer S19a Pro',
    manufacturer: 'Bitmain',
    hashrate: 110,
    hashrate_unit: 'TH/s',
    power_consumption: 2100,
    power_unit: 'W',
    efficiency: 19.09,
    efficiency_unit: 'J/TH',
    price_usd: 2200,
    release_date: '2021-03',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 11,
    name: 'IceRiver KAS KS3',
    manufacturer: 'IceRiver',
    hashrate: 18000,
    hashrate_unit: 'GH/s',
    power_consumption: 3000,
    power_unit: 'W',
    efficiency: 0.167,
    efficiency_unit: 'J/GH',
    price_usd: 4500,
    release_date: '2023-08',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 12,
    name: 'IceRiver KAS KS2 Pro',
    manufacturer: 'IceRiver',
    hashrate: 12000,
    hashrate_unit: 'GH/s',
    power_consumption: 2200,
    power_unit: 'W',
    efficiency: 0.183,
    efficiency_unit: 'J/GH',
    price_usd: 3200,
    release_date: '2023-06',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 13,
    name: 'Innosilicon A12 Pro',
    manufacturer: 'Innosilicon',
    hashrate: 2400,
    hashrate_unit: 'MH/s',
    power_consumption: 3200,
    power_unit: 'W',
    efficiency: 1.33,
    efficiency_unit: 'J/MH',
    price_usd: 3800,
    release_date: '2023-07',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 14,
    name: 'Innosilicon A11 Pro',
    manufacturer: 'Innosilicon',
    hashrate: 2000,
    hashrate_unit: 'MH/s',
    power_consumption: 2800,
    power_unit: 'W',
    efficiency: 1.4,
    efficiency_unit: 'J/MH',
    price_usd: 3200,
    release_date: '2023-03',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 15,
    name: 'Canaan AvalonMiner A1346',
    manufacturer: 'Canaan',
    hashrate: 82,
    hashrate_unit: 'TH/s',
    power_consumption: 3276,
    power_unit: 'W',
    efficiency: 40.0,
    efficiency_unit: 'J/TH',
    price_usd: 3500,
    release_date: '2023-02',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 16,
    name: 'Canaan AvalonMiner A1166 Pro',
    manufacturer: 'Canaan',
    hashrate: 82,
    hashrate_unit: 'TH/s',
    power_consumption: 2976,
    power_unit: 'W',
    efficiency: 36.3,
    efficiency_unit: 'J/TH',
    price_usd: 2800,
    release_date: '2021-11',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 17,
    name: 'StrongU STU-U6',
    manufacturer: 'StrongU',
    hashrate: 96,
    hashrate_unit: 'TH/s',
    power_consumption: 4020,
    power_unit: 'W',
    efficiency: 41.88,
    efficiency_unit: 'J/TH',
    price_usd: 2500,
    release_date: '2021-10',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 18,
    name: 'Whatsminer M53S',
    manufacturer: 'MicroBT',
    hashrate: 202,
    hashrate_unit: 'TH/s',
    power_consumption: 3584,
    power_unit: 'W',
    efficiency: 17.7,
    efficiency_unit: 'J/TH',
    price_usd: 4800,
    release_date: '2023-08',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 19,
    name: 'Antminer S21 Pro',
    manufacturer: 'Bitmain',
    hashrate: 180,
    hashrate_unit: 'TH/s',
    power_consumption: 2800,
    power_unit: 'W',
    efficiency: 15.56,
    efficiency_unit: 'J/TH',
    price_usd: 6800,
    release_date: '2023-10',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 20,
    name: 'Whatsminer M63S',
    manufacturer: 'MicroBT',
    hashrate: 170,
    hashrate_unit: 'TH/s',
    power_consumption: 2950,
    power_unit: 'W',
    efficiency: 17.4,
    efficiency_unit: 'J/TH',
    price_usd: 5200,
    release_date: '2023-12',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 21,
    name: 'Antminer L9',
    manufacturer: 'Bitmain',
    hashrate: 9300,
    hashrate_unit: 'MH/s',
    power_consumption: 3600,
    power_unit: 'W',
    efficiency: 0.387,
    efficiency_unit: 'J/MH',
    price_usd: 2200,
    release_date: '2023-08',
    cooling_type: 'Air',
    warranty_months: 12,
  },
  {
    id: 22,
    name: 'Goldshell KD6',
    manufacturer: 'Goldshell',
    hashrate: 26400,
    hashrate_unit: 'GH/s',
    power_consumption: 3600,
    power_unit: 'W',
    efficiency: 0.136,
    efficiency_unit: 'J/GH',
    price_usd: 1800,
    release_date: '2022-03',
    cooling_type: 'Air',
    warranty_months: 12,
  },
];

// Mining hosting provider data
export const PROVIDERS_DATA = [
  {
    id: 1,
    name: 'Abundant Mines',
    website: 'https://abundantmines.com',
    location: 'Cascade Locks, Oregon, USA',
    power_sources: ['Hydro'],
    cooling_type: 'Air',
    pricing_model: 'Flat Fee',
    pricing_value: 225,
    pricing_unit: '$/month/machine',
    minimum_commitment_months: 12,
    financing_available: true,
    financing_max_usd: 140000,
    financing_rate_percent: 10,
    financing_term_months: 36,
    uptime_sla_percent: 99.5,
    setup_fee_usd: 0,
    rating: 4.8,
    reviews_count: 45,
    affiliate_program: true,
    affiliate_commission_percent: 0,
  },
  {
    id: 2,
    name: 'Compass Mining',
    website: 'https://compassmining.io',
    location: 'Multiple US locations',
    power_sources: ['Mixed'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.077,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 1,
    financing_available: false,
    financing_max_usd: 0,
    financing_rate_percent: 0,
    financing_term_months: 0,
    uptime_sla_percent: 99.0,
    setup_fee_usd: 0,
    rating: 4.5,
    reviews_count: 120,
    affiliate_program: false,
    affiliate_commission_percent: 0,
  },
  {
    id: 3,
    name: 'Simple Mining',
    website: 'https://simplemining.io',
    location: 'USA',
    power_sources: ['Mixed'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.072,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 0,
    financing_available: true,
    financing_max_usd: 50000,
    financing_rate_percent: 8.5,
    financing_term_months: 24,
    uptime_sla_percent: 99.2,
    setup_fee_usd: 0,
    rating: 4.6,
    reviews_count: 85,
    affiliate_program: true,
    affiliate_commission_percent: 2,
  },
  {
    id: 4,
    name: 'EZ Blockchain',
    website: 'https://ezblockchain.net',
    location: 'Multiple US locations',
    power_sources: ['Mixed'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.055,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 12,
    financing_available: false,
    financing_max_usd: 0,
    financing_rate_percent: 0,
    financing_term_months: 0,
    uptime_sla_percent: 98.5,
    setup_fee_usd: 0,
    rating: 4.2,
    reviews_count: 60,
    affiliate_program: false,
    affiliate_commission_percent: 0,
  },
  {
    id: 5,
    name: 'Bitkern',
    website: 'https://bitkern.io',
    location: 'USA',
    power_sources: ['Hydro', 'Wind'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.065,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 36,
    financing_available: true,
    financing_max_usd: 100000,
    financing_rate_percent: 9.0,
    financing_term_months: 36,
    uptime_sla_percent: 99.0,
    setup_fee_usd: 0,
    rating: 4.7,
    reviews_count: 42,
    affiliate_program: false,
    affiliate_commission_percent: 0,
  },
  {
    id: 6,
    name: 'Uminers',
    website: 'https://uminers.io',
    location: 'Russia',
    power_sources: ['Hydro'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.063,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 24,
    financing_available: false,
    financing_max_usd: 0,
    financing_rate_percent: 0,
    financing_term_months: 0,
    uptime_sla_percent: 98.0,
    setup_fee_usd: 0,
    rating: 4.3,
    reviews_count: 35,
    affiliate_program: false,
    affiliate_commission_percent: 0,
  },
  {
    id: 7,
    name: 'BlockOps Mining',
    website: 'https://blockopsm.com',
    location: 'USA',
    power_sources: ['Mixed'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.08,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 6,
    financing_available: false,
    financing_max_usd: 0,
    financing_rate_percent: 0,
    financing_term_months: 0,
    uptime_sla_percent: 99.0,
    setup_fee_usd: 100,
    rating: 4.4,
    reviews_count: 28,
    affiliate_program: false,
    affiliate_commission_percent: 0,
  },
  {
    id: 8,
    name: 'Millionminer',
    website: 'https://millionminer.io',
    location: 'USA',
    power_sources: ['Mixed'],
    cooling_type: 'Air',
    pricing_model: 'Variable',
    pricing_value: 0.075,
    pricing_unit: '$/kWh',
    minimum_commitment_months: 0,
    financing_available: false,
    financing_max_usd: 0,
    financing_rate_percent: 0,
    financing_term_months: 0,
    uptime_sla_percent: 99.1,
    setup_fee_usd: 0,
    rating: 4.5,
    reviews_count: 50,
    affiliate_program: false,
    affiliate_commission_percent: 0,
  },
];
